apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poct.fullname" . }}-webcontent
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Hello Daniel, this is updated!</title>
        <style>
            body {
                width: 35em;
                margin: 0 auto;
                font-family: Tahoma, Verdana, Arial, sans-serif;
            }
        </style>
      </head>
      <body>
        <h1>Hello Daniel, welcome back to nginx! this is updated </h1>
        <p>If you see this page, the nginx web server is successfully updated and
        working. This line was changed to test the ConfigMap.</p>
        
        <p>For online documentation and support please refer to
        <a href="http://nginx.org/">nginx.org</a>.<br/>
        Commercial support is available at
        <a href="http://nginx.com/">nginx.com</a>.</p>
        
        <p><em>Thank you for using nginx.</em></p>
      </body>
    </html>
