{{- if .Values.sealedSecretsController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sealedSecretsController.nameOverride | default "sealed-secrets-controller" }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.sealedSecretsController.nameOverride | default "sealed-secrets-controller" }}
  template:
    metadata:
      labels:
        app: {{ .Values.sealedSecretsController.nameOverride | default "sealed-secrets-controller" }}
    spec:
      serviceAccountName: {{ .Values.sealedSecretsController.nameOverride | default "sealed-secrets-controller" }}
      containers:
        - name: controller
          image: ghcr.io/bitnami/sealed-secrets-controller:latest
{{- end }}
