{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sealed-secrets-chart.fullname" $ }}-{{ .nameSuffix }}
  namespace: {{ .namespace }}
  labels:
    app: {{ include "sealed-secrets-chart.fullname" $ }}-{{ .nameSuffix }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sealed-secrets-chart.fullname" $ }}-{{ .nameSuffix }}
  template:
    metadata:
      labels:
        app: {{ include "sealed-secrets-chart.fullname" $ }}-{{ .nameSuffix }}
    spec:
      serviceAccountName: {{ include "sealed-secrets-chart.fullname" $ }}-{{ .nameSuffix }}
      containers:
        - name: sealed-secrets-controller
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: IfNotPresent
          args:
            - "--key-prefix=sealed-secrets-key"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
{{- end }}
