{{- if .Values.sealedSecretsController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sealedSecretsController.nameOverride }}
  namespace: {{ .Values.sealedSecretsController.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.sealedSecretsController.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.sealedSecretsController.nameOverride }}
    spec:
      serviceAccountName: {{ .Values.sealedSecretsController.nameOverride }}
      containers:
      - name: sealed-secrets-controller
        image: ghcr.io/bitnami/sealed-secrets-controller:latest
        imagePullPolicy: IfNotPresent
{{- end }}




