{{- if .Values.sealedSecretsController.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ default "sealed-secrets-controller" .Values.sealedSecretsController.nameOverride }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealed-secrets-controller
subjects:
  - kind: ServiceAccount
    name: {{ default "sealed-secrets-controller" .Values.sealedSecretsController.nameOverride }}
    namespace: {{ .Values.sealedSecretsController.namespace }}
{{- end }}



