apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mariadb-operator
  template:
    metadata:
      labels:
        app: mariadb-operator
    spec:
      containers:
        - name: mariadb-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
