apiVersion: apps/v1
kind: Deployment
metadata:
  name: poct-deployment
  namespace: argotest  
  labels:
    app: poct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poct
  template:
    metadata:
      labels:
        app: poct
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: poct-pvc
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: busybox
        image: busybox
        command: ["sleep", "3600"]
        volumeMounts:
        - mountPath: "/tmp/mojgan"
          name: task-pv-storage
