apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poct-ingress
  namespace: argotest
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
   rules:
  - host: my-poct.example.com  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poct-service
            port:
              number: 80


