apiVersion: v1
kind: Service
metadata:
  name: nginx-busybox-service
  namespace: argotest
spec:
  selector:
    app: nginx-busybox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP