apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-busybox-ingress
  namespace: argotest
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-nginx.example.com  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-busybox-service
            port:
              number: 80

