apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poct.fullname" . }}-config
data:
  APP_MODE: {{ .Values.config.appMode | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  FOO: {{ .Values.config.foo | quote }}
