deployments:
  - nameSuffix: poct
    namespace: kube-system
    replicaCount: 1
    image:
      repository: bitnami/sealed-secrets-controller
      tag: "0.28.0"
  - nameSuffix: pact
    namespace: kube-system
    replicaCount: 1
    image:
      repository: bitnami/sealed-secrets-controller
      tag: "0.28.0"






