deployments:
  - nameSuffix: poct
    replicaCount: 1
    image:
      repository: bitnami/sealed-secrets-controller
      tag: "0.28.0"
  - nameSuffix: pact
    replicaCount: 1
    image:
      repository: bitnami/sealed-secrets-controller
      tag: "0.28.0"






