replicaCount: 1

nameOverride: ""
fullnameOverride: ""
namespace: kube-system

image:
  repository: bitnami/sealed-secrets-controller
  tag: "0.28.0"

sealedSecretsController:
  enabled: true   
sealedSecrets:
  enabled: true
  secretName: sealed-secrets-controller-secret







